### ISSUE TITLE
loudml-grafana-app not supporting custom bucket in LoudML (Cortex Bucket)

### ISSUE THREAD

**Issue by soumen1979** [vsergeyev/loudml-grafana-app#27]
we are truly grateful for your contribution - loudml-grafana-app (https://github.com/vsergeyev/loudml-grafana-app) – we are currently evaluating its suitability for an Observability project.

**### Our target was to create LoudML Model from Grafana UI on Cortex dataset**

For this we custom build a Cortex bucket in LoudMl and when we use LoudML CLI, we can create a Model on Cortex dataset using that bucket and can also evaluate the model. Meaning the custom bucket works fine

We added your loudml-grafana plugin with our Grafana and that works like a charm for InfluxDB dataset. 

**### Now the Problem**
But when we use that for Cortex dataset ( we enabled Cortex data source in Grafana), this gives error when we select LoudML graph from Visualization.

Attached is the Error image.

![loudml-grafana-app-error](https://user-images.githubusercontent.com/75965888/102042436-d97d0e00-3df7-11eb-9f8e-8b651a394f9f.png)

We can deep dive into it if you have some time. Looking forward to your response.

**Comment by carbapetusa** [comment]
Try Grapgh -> Stats -> LoudML Graph

**Comment by vsergeyev** [comment]
Hello @soumen1979 , this looks a similar to #25 

Fix committed for it. Please take a look.

V.

**Comment by periatrubikx** [comment]
@vsergeyev - I checked out your code and built the zip file and tried it. Still getting the same error. Could you upload a newer zip file (just in case i missed something) please? My version of grafana is 7.3.6
